### ISSUE TITLE
请问如何将新生成的libwebrtc.jar转成你项目被引用到新项目？

### ISSUE THREAD

**Issue by bianqiantan** [iQuick/WebrtcAndroid#2]
你项目中libwebrtc是以项目的形式引入，这样可以随意修改webrtc代码。而libwebrtc.jar中无法随意修改代码，请问如何将新生成的libwebrtc.jar转成你项目被引用到新项目？

**Comment by iQuick** [comment]
自己在项目下将 libwebrtc 库打包成 aar 就好了。
@bianqiantan
